

sudo: required

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output *.adoc      
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-pdf asciidoctor/docker-asciidoctor asciidoctor-pdf -D /documents/output *.adoc    

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_success:      
  - cd output ; mv README.html index.html ; cp -R ../images images
  - git init
  - git config --local user.name "Makoto Fukuda"
  - git config --local user.email "shiba.dog.leo.private@gmail.com"
  - git add -A .
  - git commit -m "Deploy to GitHub Pages"
  - git push --force --quiet origin master > /dev/null 2>&1

