language: ruby
script: "./build.sh"
branches:
  only:
  - jekyll
rvm:
- 2.1.2
env:
  global:
    secure: B/ZpOhwdAW23cU0lfmYk/ykaR0rejJi1bP401bcSYY6KdA0QtbD4JtvmX1qppbSmFYWUSjuF34vp10b1NUCl4YfUTk9Kqw1YCvalkDUzQbbM59lNBZhFFPqCvAru8+Q/85VE0knj4zy+Ofu+aPTF0ZC0d5gA6QbTFaVchO307DXcnvGlFOkKuhPVp21Sk0/FAJUkNYeqANApJGpP8Gq7n7IYw3W5oXsJp3og2c1mxv2xo2W9FQ/J45hj9/Re+kQtejyKuKgt4CIQNqdZqFvQxnNuPyaQkJjIfWHKtaKFcgjLoEM0DS3AaYi/kD6T484hkVx/F5pSrZwd1Rb+6xeCdJpHjpmN3XMrzRl0gaumMO0LlXA/L57XUvsZrc7cqH2bDM4EOjhWHvQybNx+sf8DmS7J1NSEcWoKrjcAL6fqlDrgMzo5ghCSqdheoKdyIOFKrX1o7KsFCWOp/NAtYtZZvSHl9qa7EJKo7W6gKIxtDkgVtadhyYKRXDH3zXklAcN4nHadsNUJO/Kdyg6R8YjNoDThDzNL4bsUvIR3DuImhKSGNiP9h4z0ebSlde3VFAENAjN4Qh58Ln7Wlps9/2+nbimWEeGHQY37kG5RrfTKmKVOsr5zZ3QgpbANuoKUMHYleCd7gNCXIpmu3t41uRxg8j8ZaEZvd+qCXMwaOXcauQU=
