= B2ゼミ 第8回
福田 誠 <fukuda-makoto-vb@ynu.jp>
v0.2 2021-07-14   
:toc:
:toclevels: 2
:toc-title: 内容
:sectnums:
:sectnumlevels: 2
:stem:
:eqnums: all
:dummy: {counter2:section:0}
:example-caption: 例



== 今回の目標
:dummy: {counter2:section}
:num: 0

. 正規分布の定義・性質を確認
. 多次元正規分布の定義・性質を確認
. 二次元正規分布の性質

=== 言葉の確認

* 正規分布
* 標準正規分布
* 多次元正規分布
* 単回帰係数
* ボックス・ミュラー法

== 正規分布
:dummy: {counter2:section}
:num: 0

=== 導出

偶然誤差:: 観測するごとに独立に発生する誤差

.偶然誤差に関するガウスの公理
****

. 大きさの等しい正と負の誤差は等しい確率で生じる
. 小さい誤差は大きい誤差より起こりやすい
. ある限界値より大きな誤差は実際上怒らない

****

何かしらの値を測定するとき，真の値 \(X\) から誤差 \(\varepsilon\) だけ離れた値 \(x\) を観測するとする．すなわち
\[
    \begin{align}
    \label{x:e}
        x = X + \varepsilon
    \end{align}
\]
である．
確率変数 \(\varepsilon\) の従う分布 \(f(\varepsilon)\) を考える． \( (\varepsilon, \varepsilon + d \varepsilon ) \) の範囲の誤差が観測される確率は
\[
    \begin{align}
    \label{f:e}
        f(\varepsilon) d \varepsilon
    \end{align}
\]
である．(\(\ref{x:e}\))より \( dx = d \varepsilon \) だから (\(\ref{f:e}\))は
\[\notag
    \begin{align*}
        f(x -X) d x
    \end{align*}
\]
と書ける．

ここで \(n\) 個の標本を観測することを考える．それぞれの観測値は確率変数と見ることができる．これを \(X_1, X_2, \cdots , X_n\) とおく．誤差 \(\varepsilon\) は観測するごとにそれぞれ独立に生じている．誤差が \(n\) 個の観測値 \(X_1, X_2, \dotsc , X_n\) から \(dx\) 内に入いる確率は
\[\notag
    \begin{align*}
        f(X_1 -X) d x f(X_2 -X) d x \cdots f(X_n -X) d x
    \end{align*}
\]
とかける．これを \(P(X_1, X_2, \dotsc , X_n)dx^n\) と表すと \(X_1, X_2, \dotsc , X_n\) の同時確率密度関数 \(P(X_1, X_2, \dotsc , X_n)\) は
\[
    \begin{align}
    \label{p}
        P(X_1, X_2, \cdots , X_n) = f(X_1 -X) f(X_2 -X) \cdots f(X_n -X)
    \end{align}
\]
であることがわかる．

公理1,2 より \(P\) は \(X_1 = X_2 = \cdots = X_n = X\) で最大値をとる．

一方， (\(\ref{p}\)) を \(X\) の関数 \(P(X)\) とみるとどのような \(X\) で\(P\) が最大となるかはわからない．そこで

.経験則による仮定
****
\({\rm P}(X)\)は\(X = \dfrac{x_1 + x_2 + \dotsb + x_n}{n} = \overline{X}\)で最大値をとる．すなわち
\[
    \begin{align}
    \label{hyp}
        \dfrac{d {\rm P}}{dX}(\overline{X}) = 0
    \end{align}
\]

****

という仮定をおいてみる．

(\(\ref{p}\))の対数をとって
\[\notag
    \begin{align*}
        \ln P = \sum_{i=1}^{n} \ln f(X_i - X)
    \end{align*}
\]
両辺微分して
\[\notag
    \begin{align*}
        \dfrac{P'}{P} = -\sum_{i=1}^{n} \dfrac{f'(X_i - X)}{f(X_i - X)}
    \end{align*}
\]
ここで \(X = \overline{X}\) とおくと(\ref{hyp})より
\[
    \begin{align}
    \label{gen}
        \sum_{i=1}^{n} \dfrac{f'(X_i - \overline{X})}{f(X_i - \overline{X})} = 0
    \end{align}
\]
を得る．

また定義より
\[\notag
    \begin{align*}
        \sum_{i=1}^{n} (X_i - \overline{X}) = 0
    \end{align*}
\]
を満たす．

ここで次の補題を示す．

:lem-phi: 補題
[#lem:phi.lemma, title='{lem-phi}']
****

関数 \(\phi ~ \colon ~ \mathbb{R} \to \mathbb{R}\) は二階微分可能であるとする．任意の \(n ~ (\geq 3)\)  個の独立な実数 \(x_1, x_2, \dotsc ,x_n\) が
\[
    \begin{align}
    \label{sum}
        x_1 + x_2 + \dotsb + x_n = 0
    \end{align}
\]
なる関係を満たし，関数 \(\phi\) が
\[
    \begin{align}
    \label{dphi}
        \sum_{i=1}^{n} \phi(x_i) = 0
    \end{align}
\]
を満たすとき定数 \(a\) をもちいて \(\phi (x) = ax \) とかける．

****
[.text-left]
**証明**

****

(\(\ref{dphi}\))を \(x_i ~ (1 \leq i \leq n-1)\) で偏微分して
\[\notag
    \begin{align*}
        \phi'(x_i) + \phi'(x_n) \dfrac{\partial x_n}{\partial x_i} = 0
    \end{align*}
\] 
となる．
(\(\ref{sum}\)) より \( \displaystyle x_n = -\sum_{i=1}^{n-1} x_i \) だから \(\dfrac{\partial x_n}{\partial x_i} = -1\) ．よって
\[
    \begin{align}
        \label{n}
        \phi'(x_i) = \phi'(x_n)
    \end{align}
\]
が成り立つ．

\(1 \leq j \leq n-1, ~ j\not = i\) を満たす \(j\) についても同様に
\[
    \begin{align}
        \label{m}
        \phi'(x_j) = \phi'(x_n)
    \end{align}
\]
(\(\ref{n}, \ref{m}\))より\(1 \leq j \leq n-1, ~ j\not = i\) を満たす \(i, j\) について
\[\notag
    \begin{align*}
        \phi'(x_i) = \phi'(x_j)
    \end{align*}
\]
両辺を\(x_i\)で偏微分すると，各 \(x_1, x_2, \dotsc , x_n\) は独立であったから
\[\notag
    \begin{align*}
        \phi''(x_i) = 0
    \end{align*}
\]
これより \(\phi(x) = ax+b\) とかける．(\(\ref{sum}, \ref{dphi}\)) より \(b=0\) を得る．\(\Box\)

****

\(\phi = \dfrac{f'}{f}\) として(\(\ref{gen}\))に<<lem:phi>>を適用すると
\[\notag
    \begin{align*}
        \dfrac{f'(x_i-X)}{f(x_i-X)} = a(x_i-X)
    \end{align*}
\]

ここで \(x_i\) を \(x\) ，\(X\) を \(\mu\) とおきなおすと
\[\notag
    \begin{align*}
        \dfrac{f'(x)}{f(x)} &= a(x-\mu)\\
        \therefore \quad f(x) &= C \exp\left(\dfrac{a(x-\mu)^2}{2}\right)
    \end{align*}
\]
公理3.より \( \displaystyle \lim_{x \to \pm \infty} f(x) = 0\) だから \(a<0\)とわかる．そこで \( a = -\dfrac{1}{\sigma^2} \) とおく．

規格化条件とガウス積分の公式から\(C = \dfrac{1}{\sqrt{2 \pi \sigma^2}}\) とわかる．

以上より偶然誤差は確率密度関数が
\[
    \begin{align}
        \label{reg}
        f_X(x) = \dfrac{1}{\sqrt{2 \pi \sigma^2}} \exp\left(- \dfrac{(x-\mu)^2}{2 \sigma^2 }\right)
    \end{align}
\]
で与えられる分布に従う．

ガウス分布とはガウスの公理を満たす確率密度関数のうち特に \(P'(\overline{X}) = 0\) を満たすものである．

[.text-left]
**注意**

\(n=2\) のとき，\(\phi\)は任意の奇関数となる．\(\phi(x) = ax\) は奇関数だから \(n=2\) の場合も \(\phi(x)=ax\) としてよい．

\(n=1\) のとき，\(\overline{X} = X_1\) で，仮定は公理1,2そのものである．

よって\(n=1,2\) に対しても(\(\ref{reg}\)) としても矛盾を生じない．

=== パラメタ ===

確率変数 \(X\) の確率密度関数が (\(\ref{reg}\)) で表されるとき，\(X\) は平均 \(\mu\) 分散 \(\sigma ^2\) の正規分布に従うといい，\(X \sim N(\mu, \sigma ^2)\) とかく．
\[\notag
    \begin{align*}
        E[X] =  \dfrac{1}{\sqrt{2 \pi \sigma ^2}} \int_{- \infty} ^{+ \infty} x \exp\left(- \dfrac{(x-\mu)^2}{2 \sigma^2 }\right)dx
    \end{align*}
\]
\(z = \dfrac{x-\mu}{\sigma}\) と変数変換して
\[\notag
    \begin{align*}
        E[X] =  \dfrac{1}{\sqrt{2 \pi \sigma ^2}} \int_{- \infty} ^{+ \infty} \left( \sigma^2 z + \mu \sigma \right) \exp\left(- \dfrac{z ^2}{2}\right)dz
    \end{align*}
\]
\(\displaystyle \int_{- \infty} ^{+ \infty}  z^{}  \exp\left( - \dfrac{z^2}{2}\right)dz = \left[ - \exp\left( - \dfrac{z^2}{2}\right) \right]^{+\infty}_{-\infty} = 0\) より
\[\notag
    \begin{align*}
        E[X] &=  \dfrac{\mu}{\sqrt{2 \pi}} \int_{- \infty} ^{ +\infty}  \exp\left(- \dfrac{z ^2}{2}\right)dz\\
        &=  \dfrac{\mu}{\sqrt{2 \pi}} \sqrt{2 \pi} = \mu
    \end{align*}
\]
また
\[\notag
    \begin{align*}
        E[X^2] &=  \dfrac{1}{\sqrt{2 \pi \sigma ^2}} \int_{- \infty} ^{ + \infty} x^2 \exp\left(- \dfrac{(x-\mu)^2}{2 \sigma^2 }\right)dx\\
        &=  \dfrac{1}{\sqrt{2 \pi \sigma ^2}} \int_{- \infty} ^{+ \infty} \left( \sigma^2 z + \mu \sigma \right)^2 \exp\left(- \dfrac{z ^2}{2}\right)dz
    \end{align*}
\]
ここで
\[\notag
    \begin{align*}
        \int_{- \infty} ^{ + \infty}  z^2  \exp\left( - \dfrac{z^2}{2}\right)dz &= \int_{- \infty} ^{+ \infty}  \left(-z\right) \left(- \exp\left( - \dfrac{z^2}{2}\right) \right) dz\\
        &= \left[ - z\exp\left( - \dfrac{z^2}{2}\right) \right]^{+\infty}_{-\infty} + \int_{- \infty} ^{ + \infty} \exp\left( - \dfrac{z^2}{2}\right)dz\\
        &= \sqrt{2\pi}
    \end{align*}
\]
より
\[\notag
    \begin{align*}
        E[X^2] &=  \dfrac{1}{\sqrt{2 \pi \sigma ^2}} \int_{- \infty} ^{ + \infty} \left( \sigma^2 z + \mu \sigma \right)^2 \exp\left(- \dfrac{z ^2}{2}\right)dz\\
        &=  \dfrac{1}{\sqrt{2 \pi \sigma ^2}} \int_{- \infty} ^{ + \infty} \left( \sigma^4 z ^2 + 2\mu \sigma ^3 z + \mu ^2 \sigma ^2 \right) \exp\left(- \dfrac{z ^2}{2}\right)dz\\
        &= \dfrac{1}{\sqrt{2 \pi \sigma ^2}} \left\{\sigma ^4 \sqrt{2\pi} + \mu ^2 \sigma ^2 \sqrt{2\pi} \right\} = \sigma ^2 + \mu ^2
    \end{align*}
\]
だから
\[\notag
    \begin{align*}
        V[X] &= E[X ^2] - E[X]^2\\
        &= \sigma ^2 + \mu ^2 - \mu ^2 = \sigma ^2
    \end{align*}
\]

\(X \sim N(0, 1)\) のとき\(X\) は標準正規分布に従うという．

=== モーメント母関数 ===

\[\notag
    \begin{align*}
        M_X[t] &=  \dfrac{1}{\sqrt{2 \pi \sigma ^2}} \int_{- \infty} ^{+ \infty} \exp\left(xt\right) \exp\left(- \dfrac{(x-\mu)^2}{2 \sigma^2 }\right)dx\\
        &= \exp\left( \mu t + \dfrac{\sigma ^2 t^2}{2} \right) \dfrac{1}{\sqrt{2 \pi \sigma ^2}}  \int_{- \infty} ^{+ \infty} \exp\left(- \dfrac{1}{2 \sigma^2 } \left\{ x- \left( \mu + \sigma ^2 t \right) \right\}\right)dx\\
        &= \exp\left( \mu t + \dfrac{\sigma ^2 t^2}{2} \right)
    \end{align*}
\]

=== 再生性 === 

\(X \sim N(\mu_{x}, \sigma_{xx}), Y \sim N(\mu_{y}, \sigma_{yy})\) のとき \(Z = X + Y\) の従う分布は \(N(\mu_{x} + \mu_{y}, \sigma_{xx} + \sigma_{yy})\)

\[\notag
    \begin{align*}
        f_Z (z) = \dfrac{1}{\sqrt{2 \pi \sigma_{xx} ^2}} \dfrac{1}{\sqrt{2 \pi \sigma_{yy} ^2}} \int_{-\infty}^{+\infty} \exp\left( - \dfrac{(x-\mu_{xx})^2 }{2 \sigma_{xx}} \right) \exp\left( - \dfrac{(z - x - \mu_{yy})^2 }{2 \sigma_{xx}} \right) dx
    \end{align*}
\]
\(\dfrac{1}{\sigma ^2} = \dfrac{1}{\sigma_{xx}} + \dfrac{1}{\sigma_{yy}}\) とおくと
\[\notag
    \begin{align*}
        & - \dfrac{(x-\mu_{x})^2 }{2 \sigma_{xx}}  - \dfrac{(z - x - \mu_{y})^2 }{2 \sigma_{xx}}\\
        &= -\dfrac{1}{2\sigma ^2} \left\{ x - \sigma ^2 \left( \dfrac{\mu_x}{\sigma_{xx}} + \dfrac{z - \mu_y}{\sigma_{yy}} \right) \right\} ^2 \\
        & \quad + \dfrac{\sigma^2}{2} \left( \dfrac{\mu_x}{\sigma_{xx}} + \dfrac{z - \mu_y}{\sigma_{yy}} \right) -\dfrac{1}{2} \left( \dfrac{\mu_x ^2}{\sigma_{xx}} + \dfrac{(z - \mu_y) ^2}{\sigma_{yy}} \right)\\
        &= -\dfrac{1}{2\sigma ^2} \left\{ x - \sigma ^2 \left( \dfrac{\mu_x}{\sigma_{xx}} + \dfrac{z - \mu_y}{\sigma_{yy}} \right) \right\} ^2 - \dfrac{1}{2} \dfrac{(z - \mu_{x} - \mu_{y}) ^2}{\sigma_{xx} + \sigma_{yy}}
    \end{align*}
\]
より
\[\notag
    \begin{align*}
        f_Z(z) &= \dfrac{1}{\sqrt{2 \pi \sigma_{xx} ^2}} \dfrac{1}{\sqrt{2 \pi \sigma_{yy} ^2}} \sqrt{2\pi \sigma ^2} \exp \left( - \dfrac{1}{2} \dfrac{(z - \mu_{x} - \mu_{y}) ^2}{\sigma_{xx} + \sigma_{yy}} \right)\\
        &= \dfrac{1}{\sqrt{2 \pi (\sigma_{xx} ^2 + \sigma_{yy} ^2)}} \exp \left( - \dfrac{1}{2} \dfrac{(z - \mu_{x} - \mu_{y}) ^2}{\sigma_{xx} + \sigma_{yy}} \right)
    \end{align*}
\]
だから \(Z \sim N(\mu_{x} + \mu_{y}, \sigma_{xx} + \sigma_{yy})\)

== 多次元正規分布
:dummy: {counter2:section}
:num: 0

=== 導出

\(p\) 個の確率変数 \(Z_1, Z_2, \dotsc , Z_p\) が独立に同一の分布 \(N(1,0)\) に従うとする．\(\boldsymbol{z} = (z_1, z_2, \dotsc , z_p)^T\) として確率変数ベクトル \(\boldsymbol{Z} = (Z_1, Z_2, \dotsc , Z_p)\) の同時確率密度関数 \(f_{\boldsymbol{Z}}(\boldsymbol{z})\) は 
\[
    \begin{align}
        f_{\boldsymbol{Z}}(\boldsymbol{z}) &=\prod_{i=1} ^{n} \dfrac{1}{\sqrt{2 \pi}} \exp \left(-\dfrac{z_i ^2}{2}\right)\notag\\
        &= \dfrac{1}{(\sqrt{2 \pi}) ^p} \exp \left(-\dfrac{1}{2} \sum_{i=0} ^{p} z_i^2 \right)\notag\\
        \label{fz}
        &= \dfrac{1}{(\sqrt{2 \pi}) ^p} \exp \left(-\dfrac{1}{2}\boldsymbol{z}^T \boldsymbol{z} \right)
    \end{align}
\]
である．

各 \(z_i \sim N(0,1)\) より
\[\notag
    \begin{align*}
        \boldsymbol{\mu_z} = \begin{pmatrix} \mu_{z_1} \\
        \mu_{z_2}\\
        \vdots\\
        \mu_{z_p}
        \end{pmatrix} = \begin{pmatrix} 0 \\
        0\\
        \vdots\\
        0
        \end{pmatrix}
    \end{align*}
\]
及び
\[\notag
    \begin{align*}
        \Sigma_{\boldsymbol{zz}} = E\left[ (\boldsymbol{z} - \boldsymbol{\mu}) (\boldsymbol{z} - \boldsymbol{\mu})^T \right] = \begin{pmatrix}
        1 & 0 & \cdots & 0\\
        0 & 1 & \cdots & 0\\
        \vdots & \vdots & \ddots & \vdots\\
        0 & 0 & \cdots & 1\\
        \end{pmatrix}
        = E
    \end{align*}
\]
が成り立つ． ここで正則な実対称行列 \(A\) を用いて \(\boldsymbol{Z}\) を

\[
    \begin{align}
    \label{ZtoA}
        \boldsymbol{X} = A \boldsymbol{Z} + \boldsymbol{b}
    \end{align}
\]
のように正則アフィン変換したときの\(p\) 次元確率変数ベクトル \(\boldsymbol{X} = ( X_1, X_2 , \dotsc , X_p)^T\) が 従う分布 \(f_{\boldsymbol{X}}( x_1, x_2, \cdots , x_n)\) を求める．

このとき
\[
    \begin{align}
    \label{mu}
        \boldsymbol{\mu_x} = E[\boldsymbol{X}] = A E[\boldsymbol{Z}] + \boldsymbol{b} = \boldsymbol{b}
    \end{align}
\]
である．また

\[
    \begin{align}
        \Sigma_{\boldsymbol{xx}} &= V[\boldsymbol{X}]\\
        &= E\left[ (A \boldsymbol{Z} + \boldsymbol{b} - E[\boldsymbol{X}]) (A \boldsymbol{Z} + \boldsymbol{b} - E[\boldsymbol{X}])^T \right]\notag\\
        &= E\left[ A \boldsymbol{Z} \boldsymbol{Z}^T A ^T \right]\notag\\
        &= A E\left[  \boldsymbol{Z} \boldsymbol{Z}^T \right] A^T\notag\\
        \label{sigma}
        &= A E A^T = AA^T
    \end{align}
\]
である．

(\(\ref{ZtoA}\), \(\ref{mu}\)) および\(A\) が正則であることより
\[
    \begin{align}
    \label{XtoZ}
        \boldsymbol{Z} = A ^{-1} \left( \boldsymbol{X - \mu_x} \right)
    \end{align}
\]
である．

(\(\ref{XtoZ}\)) を (\(\ref{fz}\)) に代入すると
\[\notag
    \begin{align*}
        f_{\boldsymbol{Z}}(A^{-1} \boldsymbol{ (\boldsymbol{X -\mu_x})}) &= \dfrac{1}{(\sqrt{2 \pi}) ^p} \exp \left(-\dfrac{1}{2}\boldsymbol{z}^T \boldsymbol{z} \right)\\
        &= \dfrac{1}{(\sqrt{2 \pi}) ^p} \exp \left(-\dfrac{1}{2} \left\{A^{-1} (\boldsymbol{x- \mu_x})\right\}^T \left\{A^{-1} (\boldsymbol{x- \mu_x})\right\} \right)\\
        &= \dfrac{1}{(\sqrt{2 \pi}) ^p} \exp \left(-\dfrac{1}{2} (\boldsymbol{x- \mu_x})^T (A ^{-1}) ^T  A^{-1} (\boldsymbol{x- \mu_x}) \right)\\
        &= \dfrac{1}{(\sqrt{2 \pi}) ^p} \exp \left(-\dfrac{1}{2} (\boldsymbol{x- \mu_x})^T (AA^T) ^{-1} (\boldsymbol{x- \mu_x}) \right)\\
        &=\dfrac{1}{(\sqrt{2 \pi}) ^p} \exp \left(-\dfrac{1}{2} (\boldsymbol{x- \mu_x})^T ~ \Sigma_{\boldsymbol{xx}} ^{-1} ~ (\boldsymbol{x- \mu_x}) \right)\\
    \end{align*}
\]
である．

(\(\ref{sigma}\)) より
\[\notag
    \begin{align*}
        \det \Sigma_{\boldsymbol{xx}} &= (\det A ) (\det A^T ) = (\det A )^2 \\
        |\det A| &= \sqrt{\det \Sigma_{\boldsymbol{xx}}}
    \end{align*}
\]

であることと (\(\ref{XtoZ}\)) より
\[\notag
    \begin{align*}
        \left| \det \left( \dfrac{\partial \boldsymbol{z}}{\partial \boldsymbol{x}} \right)\right| &= \left| \det \left( A^{-1}\right) \right|\\
        &= \left| \dfrac{1}{\det A} \right| = \dfrac{1}{|\det A|} \\
        &= \sqrt{\det \Sigma_{\boldsymbol{xx}}}
    \end{align*}
\]
となる．

以上より\(p\) 次元確率変数ベクトル \(\boldsymbol{X} = ( X_1, X_2 , \dotsc , X_p)^T\) が 従う分布 \(f_{\boldsymbol{X}}( \boldsymbol{x})\) は
\[\notag
    \begin{align*}
        f_{\boldsymbol{X}}( \boldsymbol{x}) &= f_{\boldsymbol{Z}}(A^{-1} \boldsymbol{ (\boldsymbol{X -\mu_x})}) \left| \det \left( \dfrac{\partial \boldsymbol{z}}{\partial \boldsymbol{x}} \right)\right|\\
        &= \dfrac{1}{(\sqrt{2 \pi}) ^p \sqrt{\det \Sigma_{\boldsymbol{xx}}}} \exp \left(-\dfrac{1}{2} (\boldsymbol{x- \mu_x})^T ~ \Sigma_{\boldsymbol{xx}} ^{-1} ~ (\boldsymbol{x- \mu_x}) \right)
    \end{align*}
\]
ここで重積分の変数変換公式を用いた．



=== モーメント母関数

\(\boldsymbol{t}\)を \(p\) 次元ベクトル \(\boldsymbol{t} = ( t_1, t_2 , \dotsc , t_p)^T\) とする．\(p\) 次元正規分布\(f_{\boldsymbol{X}}( \boldsymbol{x})\) のモーメント母関数\(M_\boldsymbol{X}(\boldsymbol{t})\)は
\[\notag
    \begin{align*}
        M_\boldsymbol{X}(\boldsymbol{t}) &= E[\boldsymbol{t}^T \boldsymbol{X}]\\
        &= \int_{D_\boldsymbol{X}}\dfrac{1}{(\sqrt{2 \pi}) ^p \sqrt{\det \Sigma_{\boldsymbol{xx}}}} \exp \left(-\dfrac{1}{2} (\boldsymbol{x- \mu_x})^T ~ \Sigma_{\boldsymbol{xx}} ^{-1} ~ (\boldsymbol{x- \mu_x}) \right) \exp\left( \boldsymbol{t}^T \boldsymbol{x} \right)  d\boldsymbol{x}
    \end{align*}
\]
指数関数 の中は
\[\notag
    \begin{align*}
        & \quad -\dfrac{1}{2} (\boldsymbol{x- \mu_x})^T ~ \Sigma_{\boldsymbol{xx}} ^{-1} ~ (\boldsymbol{x- \mu_x}) + \boldsymbol{t}^T \boldsymbol{x}\\
        &= 
    \end{align*}
\]
ここの計算ができませんでした．





[bibliography]
== 参考文献
* [[[ref:kuroki,Kuroki]]] 黒木学. 数理統計学&#8212;統計的推論の基礎&#8212; . 初版, 東京, 共立出版株式会社, 2020, 246p., ISBN 978-4-320-11429-6. 
* http://www.eng.niigata-u.ac.jp/~nomoto/7.html
* https://www.hellocybernetics.tech/entry/2016/10/06/111153#%E7%89%B9%E5%88%A5%E3%81%AA%E5%A4%9A%E6%AC%A1%E5%85%83%E6%A8%99%E6%BA%96%E6%AD%A3%E8%A6%8F%E5%88%86%E5%B8%83
* https://agirobots.com/multivariate-standard-normal-distribution/

////
* [[[ref:seki, Seki]]]  赤摂也．確率論入門．初版, 東京, 培風館, 1963, 214p., ISBN 978-4563003142
* [Sinai] Yakov G. Sinai著, 森真訳. シナイ確率論入門コース. 東京, 丸善出版株式会社, 2012, 225p., ISBN 978-4-621-06298-2
////
